=== Nils897/Webengineering/Labore/Labor2/Edward_Snowden.dtd
<!ELEMENT Edward_Snowden (Überschrift, Absatz+)>
<!ELEMENT Überschrift (#PCDATA)>
<!ELEMENT Absatz (BeschriebeneZeile*, Leerzeile*)>
<!ELEMENT BeschriebeneZeile (Normalschrift | Fettdruck | Kursiv)+>
<!ELEMENT Leerzeile EMPTY>
<!ELEMENT Normalschrift (#PCDATA)>
<!ELEMENT Fettdruck (#PCDATA)>
<!ELEMENT Kursiv (#PCDATA)>

=== Nils897/Webengineering/Labore/Labor2/Edward_Snowden.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Edward_Snowden SYSTEM "Edward_Snowden.dtd">
<Edward_Snowden>
    <Überschrift>Edward Snowden</Überschrift>
    <Absatz>
        <Leerzeile/>
    </Absatz>
    <Absatz>
        <BeschriebeneZeile>
            <Fettdruck>Edward Snowden</Fettdruck>
            <Normalschrift>ist ein</Normalschrift>
            <Kursiv>US-amerikanischer Whistleblower</Kursiv>
            <Normalschrift>und</Normalschrift>
        </BeschriebeneZeile>
        <BeschriebeneZeile>
            <Normalschrift>ehemaliger</Normalschrift>
            <Kursiv>CIA-Mitarbeiter.</Kursiv>
            <Normalschrift>Seine Enthüllungen gaben Einblicke in das</Normalschrift>
        </BeschriebeneZeile>
        <BeschriebeneZeile>
            <Normalschrift>Ausmaß der weltweiten Überwachungs- und Spionagepraktiken von</Normalschrift>
        </BeschriebeneZeile>
        <BeschriebeneZeile>
            <Normalschrift>Geheimdiensten - überwiegend jenen der Vereinigten Staaten und</Normalschrift>
        </BeschriebeneZeile>
        <BeschriebeneZeile>
            <Normalschrift>Großbritanniens. Diese lösten im Sommer 2013 die NSA-Affäre aus.</Normalschrift>
        </BeschriebeneZeile>
    </Absatz>
    <Absatz>
        <Leerzeile/>
    </Absatz>
    <Absatz>
        <BeschriebeneZeile>
            <Normalschrift>Er wurde dafür mehrfach von nichtstaatlichen Organisationen</Normalschrift>
        </BeschriebeneZeile>
        <BeschriebeneZeile>
            <Normalschrift>ausgezeichnet und für dem Friedensnobelpreis nominiert</Normalschrift>
        </BeschriebeneZeile>
    </Absatz>
</Edward_Snowden>
